version: '3.8'

services:
  conan-builder:
    build: .
    volumes:
      - .:/workspace
      - ./build/docker:/workspace/build
      - conan-cache:/root/.conan2
    working_dir: /workspace
    env_file:
      - .env
    environment:
      - CONAN_USER_HOME=/root/.conan2
    command: /bin/bash

volumes:
  conan-cache:
